### ISSUE TITLE
read_csvy doesn't read the primary example on csvy.org

### ISSUE THREAD

**Issue by MichaelChirico** [leeper/csvy#13]
Not sure if the schema is canonical and has changed, but `read_csvy` assumes there's a headline field `fields`, which is now nested in `resources[[1]]$schema$fields`.

C/P of file currently on the front page of csvy.org

```
---
name: my-dataset
resources:
- order: 1
  schema:
    fields:
    - name: var1
      type: string
    - name: var2
      type: integer
    - name: var3
      type: number
  dialect:
    csvddfVersion: 1.0
    delimiter: ","
    doubleQuote: false
    lineTerminator: "\r\n"
    quoteChar: "\""
    skipInitialSpace: true
    header: true
---
var1,var2,var3
A,1,2.0
B,3,4.3
```

Current output of `read_csvy` (CRAN):

```
read_csvy('~/data.table/inst/tests/test.csvy')
#   var1 var2 var3
# 1    A    1  2.0
# 2    B    3  4.3
```

> Warning message:
> In check_metadata(y, out) :
  Metadata is missing for variables listed in data: var1, var2, var3
